# Generated by Django 2.2.1 on 2019-09-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
    ]
