# Generated by Django 2.2.1 on 2019-09-04 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_classe', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eleve', models.CharField(max_length=30)),
                ('postnom_eleve', models.CharField(max_length=30)),
                ('prenom_eleve', models.CharField(max_length=30)),
                ('sexe_eleve', models.CharField(max_length=10)),
                ('nom_tuteur', models.CharField(max_length=30)),
                ('telephone_tuteur', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_frais', models.CharField(max_length=50)),
                ('montant', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ops', models.CharField(max_length=30)),
                ('postnom_ops', models.CharField(max_length=30)),
                ('email_ops', models.CharField(max_length=50)),
                ('telephone_ops', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_section', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=1)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Eleve')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Frais')),
                ('ops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Ops')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_option', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Eleve')),
                ('ops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Ops')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Option'),
        ),
    ]
