# Generated by Django 2.2.1 on 2019-09-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_auto_20190906_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='ops',
            name='password_ops',
            field=models.CharField(default='insoftmasomo', max_length=50),
        ),
    ]
